global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'menuapi'
    static_configs:
      - targets: ['host.docker.internal:5184'] 
  - job_name: 'weatherforecaseapi'
    static_configs:
      - targets: ['host.docker.internal:5239'] 
